"""Added User Models

Revision ID: 04da015a6200
Revises: 2c3e69045685
Create Date: 2017-11-05 16:10:29.698581

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04da015a6200'
down_revision = '2c3e69045685'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.Column('User_email', sa.String(length=255), nullable=False),
    sa.Column('User_confirmed', sa.DateTime(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('User_First_Name', sa.String(length=50), nullable=False),
    sa.Column('User_Last_Name', sa.String(length=50), nullable=False),
    sa.Column('User_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('User_id'),
    sa.UniqueConstraint('User_email')
    )
    op.drop_table('Package')
    op.drop_table('Hotel_Booking_Request')
    op.drop_table('Flight_Booking_Request')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flight_Booking_Request',
    sa.Column('fbooking_id', sa.INTEGER(), nullable=False),
    sa.Column('fbooking_departure', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fbooking_arrival', sa.VARCHAR(length=200), nullable=False),
    sa.Column('fbooking_departure_date', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fbooking_arrival_date', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fbooking_budget_range', sa.FLOAT(), nullable=True),
    sa.Column('fbooking_head_count', sa.INTEGER(), nullable=True),
    sa.Column('fbooking_email', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('fbooking_id')
    )
    op.create_table('Hotel_Booking_Request',
    sa.Column('hbooking_id', sa.INTEGER(), nullable=False),
    sa.Column('hbooking_location', sa.VARCHAR(length=200), nullable=False),
    sa.Column('hbooking_check_in', sa.VARCHAR(length=50), nullable=True),
    sa.Column('hbooking_check_out', sa.VARCHAR(length=50), nullable=True),
    sa.Column('hbooking_number_of_rooms', sa.INTEGER(), nullable=True),
    sa.Column('hbooking_budget_range', sa.FLOAT(), nullable=True),
    sa.Column('hbooking_email', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('hbooking_id')
    )
    op.create_table('Package',
    sa.Column('package_id', sa.INTEGER(), nullable=False),
    sa.Column('package_name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('package_description', sa.VARCHAR(length=200), nullable=False),
    sa.Column('package_price', sa.FLOAT(), nullable=True),
    sa.Column('package_createtime', sa.DATETIME(), nullable=True),
    sa.Column('package_updated', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.drop_table('user')
    # ### end Alembic commands ###
