"""Added emails to Request Bookings

Revision ID: 2c3e69045685
Revises: e3e41e703f65
Create Date: 2017-11-01 22:26:09.049578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c3e69045685'
down_revision = 'e3e41e703f65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Flight_Booking_Request', sa.Column('fbooking_email', sa.String(length=100), nullable=True))
    op.add_column('Hotel_Booking_Request', sa.Column('hbooking_email', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Hotel_Booking_Request', 'hbooking_email')
    op.drop_column('Flight_Booking_Request', 'fbooking_email')
    # ### end Alembic commands ###
