"""empty message

Revision ID: da5a30d78cd8
Revises: 
Create Date: 2017-11-01 17:55:34.491391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da5a30d78cd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Hotel_Booking_Request',
    sa.Column('hbooking_id', sa.Integer(), nullable=False),
    sa.Column('hbooking_location', sa.String(length=200), nullable=False),
    sa.Column('hbooking_check_in', sa.String(length=50), nullable=True),
    sa.Column('hbooking_check_out', sa.String(length=50), nullable=True),
    sa.Column('hbooking_number_of_rooms', sa.Integer(), nullable=True),
    sa.Column('hbooking_budget_range', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('hbooking_id')
    )
    op.create_table('Package',
    sa.Column('package_id', sa.Integer(), nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=False),
    sa.Column('package_description', sa.String(length=200), nullable=False),
    sa.Column('package_price', sa.Float(), nullable=True),
    sa.Column('package_createtime', sa.DateTime(), nullable=True),
    sa.Column('package_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('package_id')
    )
    op.create_table('flight_booking',
    sa.Column('fbooking_id', sa.Integer(), nullable=False),
    sa.Column('fbooking_departure', sa.String(length=100), nullable=False),
    sa.Column('fbooking_arrival', sa.String(length=200), nullable=False),
    sa.Column('fbooking_departure_date', sa.String(length=50), nullable=False),
    sa.Column('fbooking_arrival_date', sa.String(length=50), nullable=False),
    sa.Column('fbooking_budget_range', sa.Float(), nullable=True),
    sa.Column('fbooking_head_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fbooking_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('flight_booking')
    op.drop_table('Package')
    op.drop_table('Hotel_Booking_Request')
    # ### end Alembic commands ###
