"""Fixed Flight_Bookings table name

Revision ID: e3e41e703f65
Revises: da5a30d78cd8
Create Date: 2017-11-01 18:23:51.396019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e41e703f65'
down_revision = 'da5a30d78cd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Flight_Booking_Request',
    sa.Column('fbooking_id', sa.Integer(), nullable=False),
    sa.Column('fbooking_departure', sa.String(length=100), nullable=False),
    sa.Column('fbooking_arrival', sa.String(length=200), nullable=False),
    sa.Column('fbooking_departure_date', sa.String(length=50), nullable=False),
    sa.Column('fbooking_arrival_date', sa.String(length=50), nullable=False),
    sa.Column('fbooking_budget_range', sa.Float(), nullable=True),
    sa.Column('fbooking_head_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fbooking_id')
    )
    op.drop_table('flight_booking')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flight_booking',
    sa.Column('fbooking_id', sa.INTEGER(), nullable=False),
    sa.Column('fbooking_departure', sa.VARCHAR(length=100), nullable=False),
    sa.Column('fbooking_arrival', sa.VARCHAR(length=200), nullable=False),
    sa.Column('fbooking_departure_date', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fbooking_arrival_date', sa.VARCHAR(length=50), nullable=False),
    sa.Column('fbooking_budget_range', sa.FLOAT(), nullable=True),
    sa.Column('fbooking_head_count', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('fbooking_id')
    )
    op.drop_table('Flight_Booking_Request')
    # ### end Alembic commands ###
